### ISSUE TITLE
d3m exceptions StepFailedError

### ISSUE THREAD

**Issue by muneebsaif** [datamllab/autovideo#11]
d3m.exceptions.StepFailedError: Step 7 for pipeline c43355b7-0e87-499f-a9f2-defc56b6713a failed

I have trained this model using fit.py on your given dataset and saved weights in the weights directory than I run produce.py these two files run smoothly.
But when I try to run recognize.py it gives me this exception.

**Comment by daochenzha** [comment]
@muneebsaif Could you provide the full traceback. It seems that it runs smoothly in my end.

**Comment by aendrs** [comment]
I'm also having a similar problem trying to do recognition in your demo video, I'm using the **_fitted_pipeline_** that I trained using your **fit.py** example file.
I just installed yesterday autovideo and torch on a fresh python 3.8 conda environment. 
I'm using Torch version '1.12.1+cu102'. 
autovideo version 1.2.4

Could it be caused by the Torch version? Which one are you using?

Here is the error:

**predictions = produce_by_path(fitted_pipeline, video_path)**

----------------------------------------------------------------------------------------------------
[INFO:3643289 frame_extraction:110 2022-09-27 13:06:10,985] demo done with 178 out of 179 frames
/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1102, in _run_step
    self._run_primitive(step)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 988, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.multi_produce, multi_produce_arguments)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1078, in _call_primitive_method
    raise error

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1074, in _call_primitive_method
    result = method(**arguments)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/primitive_interfaces/base.py", line 426, in multi_produce
    return self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/primitive_interfaces/base.py", line 450, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/autovideo/base/transformation_base.py", line 38, in produce
    next_null_idx = inputs[inputs["transformation"].isnull()].index.tolist()[0]

IndexError: list index out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/tmp/ipykernel_3620077/2459137678.py", line 1, in <cell line: 1>
    predictions = produce_by_path(fitted_pipeline, video_path)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/autovideo/utils/axolotl_utils.py", line 104, in produce_by_path
    predictions = produce(test_dataset=dataset,

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/autovideo/utils/axolotl_utils.py", line 82, in produce
    raise pipeline_result.error

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1155, in _run
    self._do_run()

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1131, in _do_run
    self._do_run_step(step)

  File "/usr/local/anaconda3/envs/autovideo1/lib/python3.8/site-packages/d3m/runtime.py", line 1119, in _do_run_step
    raise exceptions.StepFailedError(

StepFailedError: Step 7 for pipeline 4ad30d1d-1f04-47fb-bf9b-efc55bf840f8 failed.

----------------------------------------------------------

Thanks in advance

**Comment by danieltanfh95** [comment]
Similar issue here : https://github.com/datamllab/autovideo/issues/14 with the hack required to work
