### ISSUE TITLE
examples/recogonize.py does not work out of the box. 

### ISSUE THREAD

**Issue by danieltanfh95** [datamllab/autovideo#14]
Minimum size of dataset is 4, I have the following hack in produce_by_path that works.

```
# minimum size is 4
dataset = {
    'd3mIndex': [0,1,2,3],
    'video': [video_name,video_name,video_name,video_name],
    'label': [0,0,0,0]
}
```

**Comment by danieltanfh95** [comment]
> hey, even after trying this i'm getting the same error

what did you try? You need to hack the library code for this to work

**Comment by knwachuk** [comment]
## `AttributeError: 'PipelineRun' object has no attribute 'previous_pipeline_run_id'`

### Run Command

Running the command below 

```bash
python -m examples.recognize --load_path fitted_pipeline --video_path demo.avi
```

### Error

produces the error:

```bash
Exception has occurred: AttributeError
'PipelineRun' object has no attribute 'previous_pipeline_run_id'
  File "/autovideo/autovideo/utils/axolotl_utils.py", line 80, in produce
    pipeline_result = backend.produce_pipeline(_id, [test_dataset])
  File "/autovideo/autovideo/utils/axolotl_utils.py", line 106, in produce_by_path
    predictions = produce(test_dataset=dataset,
  File "/autovideo/examples/recognize.py", line 49, in run
    predictions = produce_by_path(fitted_pipeline, args.video_path)
  File "/autovideo/examples/recognize.py", line 69, in <module>
    run(args)
AttributeError: 'PipelineRun' object has no attribute 'previous_pipeline_run_id'
```

**Comment by VSSREEKANTH** [comment]
the error is due to mismatch of  data classes used for training(fitted_pipeline), and the inference data.

**Comment by JayRGopal** [comment]
I have the same issue. Here are the relevant details.

### Environment

`torch==1.9.0
torchvision==0.10.0
numpy==1.21.2
opencv-python==4.10.0.84
-e git+https://github.com/datamllab/autovideo.git@1fa896a5d481fea7db58975f1ed13e636cfeefc7#egg=autovideo`


### Line I Ran

`python3 examples/recogonize.py --video_path videos/demo.avi --log_path logs/Oct31_log.txt --load_path weights/fitted_pipeline`


### Error Stack Trace

`Traceback (most recent call last):
  File "/Users/jaygopal/Documents/GitHub/autovideo/examples/recogonize.py", line 60, in <module>
    run(args)
  File "/Users/jaygopal/Documents/GitHub/autovideo/examples/recogonize.py", line 28, in run
    fitted_pipeline = torch.load(args.load_path, map_location="cpu")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/Users/jaygopal/Documents/GitHub/autovideo/autovideo/common/denormalize.py", line 70, in <module>
    class DenormalizePrimitive(transformer.TransformerPrimitiveBase[Inputs, Outputs, Hyperparams]):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/d3m/primitive_interfaces/base.py", line 117, in __new__
    cls.metadata.contribute_to_class(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/d3m/metadata/base.py", line 2987, in contribute_to_class
    self._generate_and_update()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/d3m/metadata/base.py", line 3125, in _generate_and_update
    generated_metadata = self._generate_metadata_for_primitive()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/d3m/metadata/base.py", line 3211, in _generate_metadata_for_primitive
    arguments, instance_methods = self._get_arguments_and_methods(hyperparams_class, type_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/d3m/metadata/base.py", line 3494, in _get_arguments_and_methods
    raise exceptions.InvalidPrimitiveCodeError(
d3m.exceptions.InvalidPrimitiveCodeError: Method 'fit_multi_produce' has an argument 'produce_methods' with type 'collections.abc.Sequence[str]' and not an expected type: typing.Sequence[str]`
