### ISSUE TITLE
AssertionError: assert os.path.exists(NO_SPLIT_TABULAR_SPLIT_PIPELINE_PATH)

### ISSUE THREAD

**Issue by akshay-gupta123** [datamllab/autovideo#7]
I am trying to run the given example of hmbd6 but getting error :
```
Traceback (most recent call last):
  File "examples/fit.py", line 56, in <module>
    run(args)
  File "examples/fit.py", line 20, in run
    from autovideo.utils import set_log_path, logger
  File "/content/autovideo/autovideo/__init__.py", line 4, in <module>
    from .utils import build_pipeline, fit, produce, fit_produce, produce_by_path, compute_accuracy_with_preds
  File "/content/autovideo/autovideo/utils/__init__.py", line 2, in <module>
    from .axolotl_utils import *
  File "/content/autovideo/autovideo/utils/axolotl_utils.py", line 12, in <module>
    from axolotl.backend.simple import SimpleRunner
  File "/usr/local/lib/python3.7/dist-packages/axolotl/backend/simple.py", line 5, in <module>
    from d3m import runtime as runtime_module
  File "/usr/local/lib/python3.7/dist-packages/d3m/runtime.py", line 23, in <module>
    from d3m.contrib import pipelines as contrib_pipelines
  File "/usr/local/lib/python3.7/dist-packages/d3m/contrib/pipelines/__init__.py", line 13, in <module>
    assert os.path.exists(NO_SPLIT_TABULAR_SPLIT_PIPELINE_PATH)
AssertionError
```

Running on Google colab. 
Code :
```
!git clone https://github.com/datamllab/autovideo.git

%cd autovideo
!pip3 install -e .

!gdown --id 1nLTjp6l6UucXEy8_eOM5Zj4Q1m79OhmT
!unzip hmdb6.zip -d datasets

!python3 examples/fit.py --alg tsn --data_dir datasets/hmdb6/ --gpu "cuda"
```

How to resolve it?

**Comment by akshay-gupta123** [comment]
Resolved

**Comment by TKovaks78** [comment]
How?
